import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'Montserrat_700Bold',
  },
  logoutButton: {
    padding: 8,
  },
  mainContent: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    fontFamily: 'SourceSansPro_400Regular',
  },
  contentContainer: {
    flex: 1,
    padding: 16,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
    fontFamily: 'Montserrat_700Bold',
  },
  statsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  statCard: {
    width: '48%',
    padding: 16,
    borderRadius: 10,
    marginBottom: 15,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  statValue: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 5,
    fontFamily: 'Montserrat_700Bold',
  },
  statLabel: {
    fontSize: 14,
    fontFamily: 'SourceSansPro_400Regular',
  },
  actionButtonsContainer: {
    marginBottom: 20,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 10,
    marginBottom: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 10,
    fontFamily: 'Montserrat_600SemiBold',
  },
  recentActivityContainer: {
    marginTop: 10,
  },
  sectionSubtitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    fontFamily: 'Montserrat_600SemiBold',
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  activityContent: {
    flex: 1,
  },
  activityTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
    fontFamily: 'Montserrat_600SemiBold',
  },
  activityMeta: {
    fontSize: 13,
    marginBottom: 2,
    fontFamily: 'SourceSansPro_400Regular',
  },
  activityStatus: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'SourceSansPro_600SemiBold',
  },
  viewButton: {
    backgroundColor: '#836EFE',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginLeft: 10,
  },
  viewButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Montserrat_500Medium',
  },
  noDataText: {
    textAlign: 'center',
    fontSize: 16,
    padding: 20,
    fontFamily: 'SourceSansPro_400Regular',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  backButton: {
    padding: 8,
    marginRight: 10,
  },
  filterContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    flexWrap: 'wrap',
  },
  filterButton: {
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    marginRight: 10,
    marginBottom: 8,
    backgroundColor: 'rgba(131, 110, 254, 0.1)',
  },
  filterButtonActive: {
    backgroundColor: '#836EFE',
  },
  filterText: {
    color: '#836EFE',
    fontSize: 14,
    fontFamily: 'SourceSansPro_600SemiBold',
  },
  filterTextActive: {
    color: '#FFFFFF',
  },
  listingItem: {
    padding: 16,
    borderRadius: 10,
    marginBottom: 15,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  listingItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  listingTitle: {
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
    fontFamily: 'Montserrat_600SemiBold',
  },
  listingStatus: {
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 10,
    fontFamily: 'SourceSansPro_600SemiBold',
  },
  listingMeta: {
    fontSize: 13,
    marginBottom: 8,
    fontFamily: 'SourceSansPro_400Regular',
  },
  listingDescription: {
    fontSize: 14,
    marginBottom: 8,
    fontFamily: 'SourceSansPro_400Regular',
  },
  listingCategory: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 12,
  },
  categoryLabel: {
    fontSize: 14,
    fontFamily: 'SourceSansPro_400Regular',
  },
  categoryValue: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'SourceSansPro_600SemiBold',
  },
  listingActions: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  actionButtonSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginRight: 10,
    marginBottom: 8,
  },
  viewActionButton: {
    backgroundColor: '#836EFE',
  },
  approveActionButton: {
    backgroundColor: '#4CAF50',
  },
  rejectActionButton: {
    backgroundColor: '#FF6347',
  },
  resetActionButton: {
    backgroundColor: '#FFA500',
  },
  actionButtonSmallText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 5,
    fontFamily: 'Montserrat_500Medium',
  },
  noDataContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 30,
  },
  userItem: {
    padding: 16,
    borderRadius: 10,
    marginBottom: 15,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  userItemContent: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  userAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#836EFE',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  userInitials: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Montserrat_700Bold',
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
    fontFamily: 'Montserrat_600SemiBold',
  },
  userEmail: {
    fontSize: 14,
    marginBottom: 6,
    fontFamily: 'SourceSansPro_400Regular',
  },
  userDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  userDetailLabel: {
    fontSize: 14,
    marginRight: 5,
    fontFamily: 'SourceSansPro_400Regular',
  },
  userDetailValue: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'SourceSansPro_600SemiBold',
  },
  userActions: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  userActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginRight: 10,
    marginBottom: 8,
  },
  userActionButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 5,
    fontFamily: 'Montserrat_500Medium',
  },
  bottomNav: {
    flexDirection: 'row',
    height: 60,
    borderTopWidth: 1,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  navItem: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navLabel: {
    fontSize: 12,
    marginTop: 3,
    fontFamily: 'SourceSansPro_400Regular',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: 20,
  },
  modalContent: {
    width: '90%',
    maxHeight: '80%',
    borderRadius: 10,
    padding: 20,
    borderWidth: 1,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    paddingBottom: 15,
    borderBottomWidth: 1,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Montserrat_700Bold',
  },
  modalBody: {
    marginBottom: 20,
  },
  listingDetailTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    fontFamily: 'Montserrat_700Bold',
  },
  listingDetailMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  listingStatusBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
    marginRight: 10,
  },
  listingStatusBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Montserrat_500Medium',
  },
  listingDetailDate: {
    fontSize: 14,
    fontFamily: 'SourceSansPro_400Regular',
  },
  listingDetailSection: {
    marginBottom: 20,
  },
  listingDetailSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
    fontFamily: 'Montserrat_600SemiBold',
  },
  listingDetailCard: {
    padding: 12,
    borderRadius: 8,
  },
  listingDetailUser: {
    fontSize: 15,
    fontWeight: '500',
    marginBottom: 4,
    fontFamily: 'Montserrat_500Medium',
  },
  listingDetailEmail: {
    fontSize: 14,
    marginBottom: 4,
    fontFamily: 'SourceSansPro_400Regular',
  },
  listingDetailPhone: {
    fontSize: 14,
    fontFamily: 'SourceSansPro_400Regular',
  },
  listingDetailDescription: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'SourceSansPro_400Regular',
  },
  listingDetailTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  listingDetailTag: {
    backgroundColor: '#836EFE',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },
  listingDetailTagText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: 'SourceSansPro_400Regular',
  },
  listingImagesContainer: {
    paddingRight: 10,
  },
  listingDetailImage: {
    width: 200,
    height: 150,
    marginRight: 10,
    borderRadius: 8,
  },
  noImagesText: {
    fontSize: 14,
    fontStyle: 'italic',
    marginBottom: 10,
    fontFamily: 'SourceSansPro_400Regular',
  },
  modalActions: {
    marginTop: 10,
  },
  approveButton: {
    backgroundColor: '#4CAF50',
    marginBottom: 10,
  },
  rejectButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FF6347',
    marginBottom: 10,
  },
  rejectButtonText: {
    color: '#FF6347',
  },
  resetButton: {
    backgroundColor: '#FFA500',
  },
  confirmModalContent: {
    width: '90%',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  warningIconContainer: {
    marginBottom: 15,
  },
  confirmModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
    fontFamily: 'Montserrat_700Bold',
  },
  confirmModalText: {
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 10,
    lineHeight: 22,
    fontFamily: 'SourceSansPro_400Regular',
  },
  confirmModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 20,
  },
  confirmModalButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    width: '48%',
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#F2F2F2',
  },
  cancelButtonText: {
    color: '#333333',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Montserrat_600SemiBold',
  },
  confirmButton: {
    backgroundColor: '#FF6347',
  },
  confirmButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Montserrat_600SemiBold',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
});
