export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SET_REFRESHING = 'SET_REFRESHING';
export const SET_FILTER_STATUS = 'SET_FILTER_STATUS';
export const UPDATE_LISTING_STATUS = 'UPDATE_LISTING_STATUS';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';